spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop


params:
  username: ${/dev/exercise/username}
  password: ${/dev/exercise/password}
